import type { Block } from 'payload';

export const IconLexicalBlock: Block = {
  slug: 'iconLexical',
  interfaceName: 'IconLexicalBlock',
  fields: [
    {
      name: 'iconName',
      type: 'select',
      required: true,
      defaultValue: 'info',
      options: [
        { label: 'Alert', value: 'alert-triangle' },
        { label: 'Arrow Right', value: 'arrow-right' },
        { label: 'Baby', value: 'baby' },
        { label: 'Bookmark', value: 'bookmark' },
        { label: 'Calendar', value: 'calendar' },
        { label: 'Camera', value: 'camera' },
        { label: 'Check', value: 'check' },
        { label: 'Clipboard Check', value: 'clipboard-check' },
        { label: 'Clock', value: 'clock' },
        { label: 'File Text', value: 'file-text' },
        { label: 'Fish', value: 'fish' },
        { label: 'Flag', value: 'flag' },
        { label: 'Flame', value: 'flame' },
        { label: 'Globe', value: 'globe' },
        { label: 'Heart', value: 'heart' },
        { label: 'Info', value: 'info' },
        { label: 'Mail', value: 'mail' },
        { label: 'Map', value: 'map' },
        { label: 'Map Pin', value: 'map-pin' },
        { label: 'Newspaper', value: 'newspaper' },
        { label: 'Phone', value: 'phone' },
        { label: 'Scroll', value: 'scroll' },
        { label: 'Smile', value: 'smile' },
        { label: 'Star', value: 'star' },
        { label: 'Trash', value: 'trash' },
        { label: 'Trash 2', value: 'trash2' },
        { label: 'Trending Up', value: 'trending-up' },
        { label: 'User', value: 'user' },
        { label: 'Users', value: 'users' },
        { label: 'X', value: 'x' },
      ],
    },
    {
      name: 'size',
      type: 'select',
      defaultValue: 'medium',
      required: true,
      options: [
        { label: 'Small (16px)', value: 'small' },
        { label: 'Medium (24px)', value: 'medium' },
        { label: 'Large (32px)', value: 'large' },
        { label: 'Extra large (50px)', value: 'xlarge' },
      ],
    },
    {
      name: 'color',
      type: 'select',
      defaultValue: 'black',
      required: true,
      options: [
        { label: 'Black', value: 'black' },
        { label: 'White', value: 'white' },
        { label: 'Green', value: 'green' },
        { label: 'Blue', value: 'blue' },
      ],
    },
  ],
  labels: {
    singular: 'Icon',
    plural: 'Icons',
  },
};
